### ISSUE TITLE
Compression: compr([seq, kid]) + ciph vs. compr([seq, kid, ciph])

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#106]
With how I'm using CBOR, it's a bit tricky to find and strip the sequence introducing the CBOR-encoded ciphertext; what I'm actually doing is encoding [seq, kid] (a 2-long list) and then making it look like a 3-long at the compression step.

Other implementors (@jimsch), how was your experience implementing it? IMO it would be more straightforward to specify serializing and compressing the 2-long list, and then appending the ciphertext to it.

If this sounds like something we could do, I'd happily write up a pull request for it.

**Comment by jimsch** [comment]
I actually ended up suggesting that some other changes be made.  I don't use CBOR to do the encoding of this because I just found it too hard.  

I suggest doing 1 byte of header, the kid value, a byte of length, the kid and then the body.  Looks nothing like CBOR and should not be presented as if it were.

**Comment by fpalombini** [comment]
@jimsch just to make sure we got this right, how would you compress this COSE_Encrypt0 with your proposal? (kid: h'25', partial IV: h'05')

[h'a2044125064105', {}, h'aea0155667924dff8a24e4cb35b9']

**Comment by jimsch** [comment]
I would make the first byte be a set of flags and a length for the kid - similar but not quite like what is there now.  So you would have 0bcdeggg  - where a is zero, b-e are flags and g is the length of the partial IV.  Thus you get
0x09 05 01 25 ae a0 15 56 67 92 4d ff 8a 24 e4 cb 35 b9
- I am using 
e - there exists a kid
d - there exists a counter signature

**Comment by chrysn** [comment]
No objections from me against directly doing bit-fiddling directly instead of after CBOR.

The -02 version has the nice property of allowing detection of uncompressed COSE structures; Jim's draft preserves that (as does any compressed data format where the most significant bit is always 0), so +1 from me.

**Comment by jimsch** [comment]
I agree with the desire to allow for uncompressed COSE to occur in messages.  This may become necessary at some point in the future if there is a need to carry additional protected attributes in the COSE message.  The only worry I have is should there be the ability to have more bits so that a longer IV can be supported.  I don't think this matters until we get to a post quantum world where we may get 256-bit block sizes.

**Comment by jimsch** [comment]
Post reading the multicast draft - may need to have a bit reserved for group id.
