### ISSUE TITLE
Change "Unprotected/Protected CoAP message" terminology

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#135]
We have had some confusion around the terminology "Unprotected/Protected CoAP message". The unprotected CoAP message is the very message the becomes protected by CoAP, and the protected CoAP message contains unprotected options. An alternative is to use the terminology "inner/outer CoAP message" instead, where the inner message is that which partially is wrapped by COSE (corresponding to the "unprotected" message) and the outer message is that which is actually sent (corresponding to the "protected" message). This would be aligned with the terms "inner" and "outer" options: the inner options then becomes the options of the inner CoAP message, and the outer options the options of the outer CoAP message.

 Any views on that?

**Comment by cabo** [comment]
Sounds good to me.

(The confusion about protected/unprotected is well known from other terminologies, prompting terms such as "red/black", which then generate their own confusion...  Outer/Inner is clear.  We used the same pair in RFC 5856.)

**Comment by cabo** [comment]
(Wow, there even is a Wikipedia article on red/black now :-)

https://en.wikipedia.org/wiki/Red/black_concept

**Comment by fpalombini** [comment]
I don't think switching to inner/outer for CoAP messages is the right choice.
Just to make it clear what I mean from "protected/unprotected CoAP":

```
                                 +-------------------+
CoAP "unprotected" message ----> | OSCOAP processing | -------> CoAP "protected" message 
                                 +-------------------+          (includes the OSCOAP option)
```

I am not convinced that using the term "inner" and "outer" simplify things. To me, these terms only make sense with some specification next to it (inner/outer of what?). They work for the options (and other message fields) since they are "inner/outer of the COSE object". BUT the COSE object is contained in the CoAP message. So the inner CoAP message would be inner of the COSE object? Ie is it the part that is protected with COSE? That's not exactly the "unprotected" CoAP message (the CoAP message before OSCOAP processing), since not the whole CoAP message is wrapped in COSE, as you say Göran.

I don't think this terminology is much more intuitive than "protected/unprotected", and I don't think talking about "inner/outer CoAP message" adds anything compared to talking about "inner/outer message fields" (terms that we use already). I do agree that we should probably specify better what unprotected/protected means, or remove that terminology if we can't solve the ambiguity.

I'd like to hear more from the people that found the terms "protected/unprotected CoAP message" confusing, what was the confusion there?

**Comment by cabo** [comment]
I think that it is confusing if the "protected message" is not the message that is being protected (the unprotected message is protected; the protected message is designed to be left unprotected).

**Comment by fpalombini** [comment]
Ah I see. Then we should probably clarify that "protected" means that the message went through the OSCOAP processing already (already contains a object-security option) and should not go through it again. 
"Protected" in this case does not mean "is going to be protected" but "was protected". 
Equally, "unprotected" means "has not gone through the OSCOAP processing yet", so it is going to be. That's fair, it should be better specified I think.

**Comment by gselander** [comment]
Still, we would have things like "the options in the protected CoAP message are not the protected CoAP options". How about "(original) CoAP message" and "OSCOAP message"? Where the OSCOAP message is defined to be the CoAP message with the Object-Security option.

Other views?

**Comment by chrysn** [comment]
I too found the protected/unprotected terminology confusing (the common terminology problem of participles -- are things already X-ed, or do they become X-ed?).

Any of "inner"/"outer", "original"/"oscoap message" and "red"/"black" would be enhancements over that IMO, with preferences for the first.
