### ISSUE TITLE
Generalizing the bitflip BF() for multicast?

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#155]
After reviewing the newly added section on "Nonce generation examples", reviewing the multicast draft, and suggesting to make CCM* MTI, and thinking about how to reduce message overhead, I think the bitflip should be generalized for multicast. I think this also makes the Nonce generation simpler to understand.

The idea is to use the endpoint IDs instead of a single bit. The nonce would simply be:

"Common IV"  XOR  ( "ID of endpoint generating Partial IV"  ||  "Partial IV" )

Using the notation from the newly added section "Nonce generation examples":

* Example 1a. Ordinary request/response.

 -> key = K1, nonce = CIV XOR ( ID1 || PIV1 ) 
 <- key = K2, nonce = CIV XOR ( ID1 || PIV1 )

* Example 1b. Observe.

 -> key = K1, nonce = CIV XOR ( ID1 || PIV1 ) 
 <- key = K2, nonce = CIV XOR ( ID2 || PIV2 )

* Example 1c. Multicast

 -> key = K1, nonce = CIV XOR ( ID1 || PIV1 ) 
 <- key = K2, nonce = CIV XOR ( ID1 || PIV1 )
 <- key = K3, nonce = CIV XOR ( ID1 || PIV1 )

* Example 2a. Ordinary request/response.

 <- key = K2, nonce = CIV XOR ( ID1 || PIV1 )
 -> key = K1, nonce = CIV XOR ( ID1 || PIV1 ) 

 * Example 2b. Observe.

 <- key = K2, nonce = CIV XOR ( ID2 || PIV2 )
 -> key = K1, nonce = CIV XOR ( ID1 || PIV1 ) 

* Example 2c. Multicast

 <- key = K2, nonce = CIV XOR ( ID2 || PIV2 )
 -> key = K1, nonce = CIV XOR ( ID2 || PIV2 ) 
 -> key = K3, nonce = CIV XOR ( ID2 || PIV2 )

The nonce length could be split up in

+--------------------+---------------+
|   Fixed-Distinct   |    Counter    |
+--------------------+---------------+

Where Counter could be 6 bytes and Fixed-Distinct could be the rest. For CCM* the Fixed-Distinct would then be 7 bytes.

Benefits:

+ This is easier to unsderstand and analyze than the kinda hand to get bitflip. The PIVs are now clearly "belonging" to an Sender ID.

+ This significantly reduces per packet overhead for multicast responses

+ Makes OSCOAP and multicast OSCOAP more similar

Disadvantages:

- The possible length of Sender ID is shortened, is this really a problem? As I see it, there will be a key management protocol (ACE, Group Manager, EDHOC, or TLS replacement for EDHOC) that manages endpoint IDs in order to ensure their uniqueness.

**Comment by fpalombini** [comment]
> Example 2a. Ordinary request/response.
> <- key = K2, nonce = CIV XOR ( ID1 || PIV1 )
> -> key = K1, nonce = CIV XOR ( ID1 || PIV1 )

This was supposed to be as follows, right?

Example 2a. Ordinary request/response.
<- key = K2, nonce = CIV XOR ( ID2 || PIV2 )
-> key = K1, nonce = CIV XOR ( ID2 || PIV2 )

Sorry I am missing something. How does this change affect packet overhead for multicast responses?
Otherwise I agree with simplicity and coherency arguments :)

(Also, ping @marco-tiloca-sics )

**Comment by jimsch** [comment]
Two comments right off the bat.  1) What happens when we switch to an algorithm which is not CCM (specifically the version we have chosen.  2) This is making an assumption that all ids are going to be distinct within the seven bytes.  If there is a collision of names then you are going to lose the IV uniqueness.

The bit-flip version may also have some nice matching properties which this is going to loose.

**Comment by fpalombini** [comment]
We have fixed the maximum length of the Partial IV so that it fits all supported COSE algorithms, the Sender ID length being dependent on it (max size(Sender ID) = size(nonce) - max size(Partial IV)).  And we chose this fixed length so that we think it is not constrained neither in number of messages nor in number of unique Sender IDs.
(feel free to reopen if this response is not satisfying)
