### ISSUE TITLE
Protection of Errors

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#171]
My understanding after talking to Göran was that errors (i.e. reponse codes 4.xx and 5.xx) were not protected, but I cannot find anything in the document about this. Following the current document would encrypt all responses including errors (as far as I can see).

If the errors are encrypted then an outer max-age should probably be allowed, e.g. in 5.03 Service Unavailable.

**Comment by jimsch** [comment]
I would expect that some errors are going to be protected and some are not.  It would depend on how far in the processing things have gotten.   Errors before doing the OSCOAP processing are going to be unprotected and errors afterwards are going to be protected.  I think this means that it might be inconsistent about which errors are going to be encrypted because it will depend on how the code is laid out.

**Comment by gselander** [comment]
In general CoAP errors should be protected. However, errors in security context, verification and other OSCOAP related errors may not be possible to protect because it may not be clear that both client and server can process the message. (The latter applies to all 4.0x errors described in the current draft.) We should make this more clear.
