### ISSUE TITLE
Extend discussion in Security Considerations about traffic analysis 

### ISSUE THREAD

**Issue by Gunzter** [core-wg/oscoap#172]
In the Security Considerations section, last paragraph, attacks on lengths of messages is addressed. The section only deals with contents of messages and does not mention URI-paths. 

URI-paths can be learned from ./well-know/core (assuming the current unprotected state of that resource), if each resource has a distinct length a malicious user can learn the destination of messages sent to a server. 

One solution to solve this would be to name resources "000", "001", etc. keeping the length constant. Adding a separate resource, for example ./well-known/mapping, that provides mapping, "000" - light, "000" - temperature, etc. can mitigate this problem. Resources can also be guessed from the length of responses, I see this as unavoidable, unless extensive padding is used.

**Comment by jimsch** [comment]
I would agree that this is something to be addressed.  The same issue would also arise with uri-queries, location-paths and locations-queries.  The only answer that I see that could be done to solve this is to add a padding option to the headers.  I don't think that this can really be solved in this document.  It may be that we should produce a separate document on traffic analysis because it might want to look at other things such as proxy interactions as well.

**Comment by Gunzter** [comment]
I think the only thing that can be done in the document is to warn about potential issues, like posting "ON"/"OFF" to toggle a light and having resources names "/light" and "/lock".
The mitigation that can be proposed is to use for example "1"/"0" to toggle a light and keeping resource names of uniform length. draft-ietf-tls-tls13-21 Appendix E.3 discuss this kind of problem.
