### ISSUE TITLE
NON and non-

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#199]
The current text use non-observe, non-cachable etc, but also NON-message as an abbreviation for a non-confirmable message. This could be confusing.

- I suggest writing Non-confirmable message (NON) instead of NON-message (this aligns with 7252)

- I also suggest writing "request is carried/sent in a in a Non-confirmable message" instead of "request is a NON-message" (this aligns with 7252)

**Comment by jimsch** [comment]
Alternative would be "is sent in a message with message type 'NON'"  But that or 1 would be my preferred text.  Don't make people try to figure out too much

**Comment by fpalombini** [comment]
when I do a search for "NON-messages" I don't find anything in the document. Jim said "NON message" is not ambiguous in his opinion.

I think to improve the text we can replace "NON messages" with "messages of type 'NON'". I would be against using only "Non-confirmable message", since as Jim pointed out 'ACK' messages are also Non-confirmable (by definition). What do you say John?

**Comment by fpalombini** [comment]
I think the point @jimsch was making (offline) was that:
- in RFC7252 the term "non-confirmable" is defined as "does not need ack back". In that sense, ACK messages are non-confirmable.
- also in RFC7252 the "non-confirmable (NON) message type" is a specific type, different from ACK. ACK is not NON.

Because of this "ambiguity" he would rather us not use the term "non-confirmable" unless followed by either "NON" or "Message type" (or something of that sort).

**Comment by fpalombini** [comment]
So taking Carsten point in consideration too, proposal: replace "NON messages" with "messages of type Non-confirmable (NON)"

**Comment by fpalombini** [comment]
I know we are off topic now :) but just wanted to point out section 1.2 of RFC7252, that says:
 
>       Non-confirmable Message
>       Some other messages do not require an acknowledgement.  This is
>       particularly true for messages that are repeated regularly for
>       application requirements, such as repeated readings from a sensor.

Even though the clarification you make about message id is valid for (message of type) Non-confirmable vs Ack, the definition of the term "non-confirmable" above still applies to ACK type messages.

What I mean, is that I disagree partially with what you wrote above: I think in RFC7252 the term NON (or when spelled out Non-confirmable meaning the message type) is reserved for messages that set a message-ID but do not require ACK. The term "non-confirmable" as defined above does not mention message-ID.

**Comment by fpalombini** [comment]
OK so thinking more about it, we should probably not specify messaging layer behavior in OSCORE. This means that we should not distinguish between CON and NON OSCORE failures, and only *optional* error response should be defined in OSCORE.
