### ISSUE TITLE
Language around Observe and Notifications

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscoap#222]
"In case of Observe ({{observe}}) the Partial IV "

This is not well defined. Is an Error notification included here or not? Such an answer is a response to an observe request but the error does not contain an observe option. Need to go through the document.

RFC7641 is not perfectly really clear in some cases either:

"The only difference between a notification and a normal response is the presence of the Observe Option."

"Non-2.xx responses do not include an Observe Option."

"sending a notification with an appropriate response code (such as 4.04 Not Found)"

**Comment by fpalombini** [comment]
From the observe spec, I understood:
- when successful, notifications include the observe option
- when errors are returned, notifications do not include the observe option. Also, as a result of the error notification, the client is removed from the list of observe and it’s not going to receive any additional notification.

I think the text you pointed out is not confusing, since we do not talk about notification but “messages with Observe option” or “when Observe is used”. Basically we treat “error notifications” exactly as normal response (not sending the partial IV).

I don’t think we have anything to modify in the text, but I agree we should check if we talk about notifications anywhere else in the text, and if we do, replace with “successful notifications” or “responses including the Observe option”

**Comment by jimsch** [comment]
My expectation on the IV to be used is going to be on which it occurs.  If it occurs on the first response from the server, then a partial IV would not be included.  If you have sent a series of observers and then have an error I would expect the response to look just like a success observe response in terms of how the server generates an IV.  You are not striking something from the cache window so a new IV is needed.

**Comment by emanjon** [comment]
@jimsch Yes, that is exactly what I expect as well.

**Comment by boaks** [comment]
https://tools.ietf.org/html/draft-ietf-core-object-security-12#section-4.2

> After that, the sending endpoint writes an Outer Code to the OSCORE
>    message.  The Outer Code SHALL be set to 0.02 (POST) or 0.05 (FETCH)
>    for requests.  For non-Observe requests the client SHALL set the
>    Outer Code to 0.02 (POST).  For responses, the sending endpoint SHALL
>    respond with Outer Code 2.04 (Changed) to 0.02 (POST) requests, and
>    with Outer Code 2.05 (Content) to 0.05 (FETCH) requests.  Using FETCH
>    with Observe allows OSCORE to be compliant with the Observe
>    processing in OSCORE-unaware intermediaries.  The choice of POST and
>    FETCH [RFC8132] allows all OSCORE messages to have payload.

Does "none-Observe requests" include request to cancel the observe?

https://tools.ietf.org/html/rfc7641#section-3.6

> In some circumstances, it may be desirable to cancel an observation
>    and release the resources allocated by the server to it more eagerly.
>    In this case, a client MAY explicitly deregister by issuing a GET
>    request that has the Token field set to the token of the observation
>    to be cancelled and includes an Observe Option with the value set to
>    1 (deregister).  All other options MUST be identical to those in the
>    registration request except for the set of ETag Options.  When the
>    server receives such a request, it will remove any matching entry
>    from the list of observers and process the GET request as usual. 

The cancel request uses option observe with value 1 (instead of 0).
Should that use POST or FETCH?

**Comment by gselander** [comment]
Thanks for the reminder that we need to clean up the list of issues!

The description of using FETCH is simplified, here is the version of the latest version of the draft.

https://core-wg.github.io/oscoap/draft-ietf-core-object-security.html#rfc.section.4.1.3.5

"Since POST with Observe is not defined, for messages with Observe, the Outer Code MUST be set to 0.05 (FETCH) for requests and to 2.05 (Content) for responses (see Section 4.2)."

So FETCH applies to registrations as well as cancellations. 

Hope that helps.

**Comment by boaks** [comment]
Thanks! It helps.
