### ISSUE TITLE
Improved protection of notifications

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#223]
Even if Observe can be removed in the request (by proxy or server), when the server does send a
notification, the Observe option is not allowed to be removed by an intermediate. 

But currently we don’t protect the information that a response is a notification. As a consequence, if the client sends an ordinary request, an on-path attacker can add an Observe option. If the request
results in notifications, the attacker can select which notification goes through and remove the Observe option, thereby deciding which (encrypted) answer that the client should see, and that will verify as a single response to the client. We should protect against this.

**Comment by gselander** [comment]
One solution is to use the inner Observe option message field. This enables three bits of information to be protected end-to-end: 

- the client requested registration
- the client requested de-registration
- the server sent a notification 
(We could recommend the integer value 2 as a dummy value for Inner Observe in case of notifications.)
 
If the application does not support CoAP proxies (as is the case in many current LwM2M deployments) then there is no need for an Outer Observe,  the non-special Inner processing is sufficient.

In order to support CoAP proxies we would however need to add an additional Outer Observe  message field, which would work in the same way as that currently specified. 

If both Inner and Outer are received and Inner verified, the inner is discarded and processing is as currently defined.

Receiving an Outer but not Inner Observe is an error. 

The endpoint receiving an Inner but not Outer option needs to know if the application allows to only use Inner Observe (e.g. in the case of LwM2M V1.0). If it does, then the straightforward Inner processing rules apply. If it doesn't the currently defined processing applies.

This solution adds more processing options and the size of the dummy inner option in case both Inner and Outer Observe are used, but also more verification points which leaves less room for error.

@chrysn, @jimsch you were deeply involved in the discussion last time, what is your view?

**Comment by jimsch** [comment]
Observe is allowed to be removed by an intermediary.  Observe is between you and the next intermediary and not necessarily with the final end point.

**Comment by gselander** [comment]
The starting point for this issue was this comment:

https://github.com/core-wg/oscoap/commit/d7d7ead8f16ff4eb689ae97c32f0cf6b23839d55#commitcomment-28289815

My understanding is that Observe is allowed to be removed in a request by an intermediate device and server, but not in the response. I might have misunderstood.

**Comment by jimsch** [comment]
From RFC 7641 - In this case, the client registers its interest with the first intermediary towards the server, acting as if it was communicating with the server itself

This means that the intermediary is who the observe is registered with.  And that intermediary could decide that it is going to stop supporting this observe relationship.

**Comment by gselander** [comment]
If it is the case that this issue may be the result from legitimate Observe processing, then we should anyway consider to use the Inner Observe option to at least allow the endpoints to get informed about their intents. We could use essentially the same processing as currently defined driven by the Outer option, but allow an application dependent policy to be a function of the Inner option. For example, some applications may require an additional Inner Observe to register/deregister.  After all, Observe with OSCORE is not meaningful unless required by the endpoints.

Does it make sense?

**Comment by jimsch** [comment]
Going back to the start of the message.  Lets address the assumptions that you have:

If the observe option is removed by an intermediary, then any closer intermediaries would tear down the fact that an observer is going on.  Any further observes from the server would then go into the ether.

The message that was encrypted and sent would still decrypt just fine with either my or Christian's code base.  If there is a partialIV in the message, we both always use it rather than using a reflected value.  This is independent of the existence of the Observe option for two reasons (for me).  First, there is always the question of using the reflected vs generated partialIV on the first observation response.  Even if you use the reflected on the first, if it gets lost or a second one comes in first then you need to be able to handle this.  Second, is that this is always going to be the case when a multi-person conversation starts.

If the observe is added, then the client would still decrypt the message just fine, look at the observe option and say what is this and promptly ignore it.  Further messages would be dropped on the floor as not matching a request.

There might be an interesting question on protecting the ACK from the client to the server, but that would be a separate issue and probably does not need to be done as the attacker could just drop the message instead of changing it.

**Comment by gselander** [comment]
Thanks Jim, this is all well securing the actions allowed by RFC 7641. What I'm thinking of is the trust model of RFC 7641 with an end-to-end security perspective. Even if endpoints can adequately handle notifications and single responses in this way, the fact that an intermediary can register, de-register and change between notifications and responses without the endpoints being aware of it may be used as easily initiated DoS attacks, and depending on application this may be an issue.

One way to handle this is to allow endpoints to optionally use Inner Observe. An implementation would be allowed to ignore the inner observe and process the message as your implementation does today. But some applications can make use of inner observe for making decisions as in the example I gave above: if an application has as policy to also use inner observe for registration, when a server receives only an outer observe 0 it can respond with a non-observe response. Or if an outer deregistration comes without an inner this may trigger some action in the application.

We may even go one step further and allow the use of inner observe only - providing an optimization and better DoS mitigation for applications without CoAP proxies or where intermediary nodes accept multiple responses to a request. 

We may want to include this in the specification or in an appendix. I haven't looked at the processing, but perhaps the former version (inner observe can always be ignored) can be included in the specification without major change and the latter (inner observe only is allowed) can be discussed in an appendix.

What do you think?

**Comment by chrysn** [comment]
> If the application does not support CoAP proxies (as is the case in
> many current LwM2M deployments) then there is no need for an Outer
> Observe,  the non-special Inner processing is sufficient.

I think that using inner-only is detrimental to interoperability. How
would you know that there are no transparent (aka interception) proxies
in the game? If some are, the first notification would appear like a
"client forgot about the observation" to the server.

> The starting point for this issue was this comment:
> d7d7ead#commitcomment-28289815

IIUC, the reason why we're discussing this in the context of the above
is that an inner (2.05-obs, 2.05-obs, 4.04) would look like (2.05-obs,
2.05-obs, 2.05...oups) on the outside.

We're already bending backwards by (ab)using FETCH to work around
observe only having been extended to FETCH but not to POST. Under the
same criteria by which we entered that route ("we want to pass proxies
that know nothing of observe fixes we asked for"), we should allow a
4.00 response for that case, which has an Object-Securty option and
payload just like the other FETCH responses.


As for the trust model discussion, I think Jim hit the point with the
topic of protected ACKs, and also that it's not worse than just
swallowing notifications.

IMO we should get a clearer view of what our threats, and how much state
we can and want to introduce, before we think of solutions. As I see
your attack, a adversary proxy (be it transparent or explicit) wants to
impede data flow in a system by hiding notifications from a client while
still forwarding its regular requests. (Stopping anything would be just
as possible but more obvious). What that adversary can now do is to
forward the observation but never send notifications to the client (or
delay them unduely). Neither legitimate party would know of this, and I
do not see how an inner observation option could mitigate that.


I think that for that scenario, the best we can do easily (ie. w/o
building a streaming protocol that accounts for lost messages) is to use
appropriate Max-Age values. If a resource becomes stale, the client can
renew the observation (or start a new one, IMO there is no difference),
and if the server comes back with a different response even though the
client though it had an active observation, that raises suspicions on
the client side if it happens more often than statistical race
conditions predict.

**Comment by gselander** [comment]
Thanks Christian, point taken about making the objectives clearer. I apologize for using this issue to think aloud. I try to be more specific here.

Current specification allows an on-path attackers, not only proxies, to make any changes to Observe. For example, a request could become a notification. While it is true that RFC7641 allows intermediaries to fulfil a single request by registering an Observation, the client can only make use of a single response and this can be easily misused for DoS. 

Since a legitimate Observe intermediary is transferring the OSCORE option and payload to the new request, we can contain protect information about the intention of the client endpoint (to make Observe 0, 1 or not make Observe) to the server endpoint, which can respond based on this. This can be Inner Observe or something else.

In case we use inner observe it is tempting to allow inner-only for an end-to-end protected Observe. This is not how RFC 7641 defines it, but end-to-end security is not an objective of RFC 7641. For example, if the client and server agreed to use inner only, then all OSCORE processing would be very simple and notifications could be just inner observe 2, which is processed like any inner option. This would require intermediaries, if present, to allow multiple responses of a request.

Also, allowing inner-only probably implies defining more that one kind of Observe processing in OSCORE, so we would need to have a parameter specifying what kind.

But threat-wise I think we should at least address the attack above.

**Comment by chrysn** [comment]
Let me rephrase that to verify I see what you mean:

An on-path attacker[1] adds an Observe option to a valid request, which
causes the server to spend excessive resources (sending many
notifications). The server believes this to be justified by authority of
the client, while the client intended no such thing.


To this, an inner observe option on requests would be a viable solution
(it could stay outer-only for responses for this consideration).

Another solution without the byte overhead but admittedly with the
potential of added fragility or decreased agility (eg. once someone
steps forward and says that POST-observe is OK and 2.xx-no-more-observe
is too) would be to add the outer method to the AAD and only accept
observations from FETCH requests.

(Because in order for the above attack to pass, the attacker needs to
change the the POST into a FETCH, and while a proxy can legitimately
strip an Observe and we can't make it Class-I for that reason, we can
with the outer code).

[1]: I was using "proxy" and "intermediary" & co interchangably because
I think of transparent proxies too.

-- 
To use raw power is to make yourself infinitely vulnerable to greater powers.
  -- Bene Gesserit axiom

**Comment by gselander** [comment]
Yes. The attack would also be against the client which will receive notifications it has not requested. And the client may be unable to deregister if the attacker/intermediary/etc. can change the Observe option on messages passing.

I did not go into the POST/FETCH part, but, yes, since the outer code is only a dummy it may be changed too. Using AAD in some way is possible, but that would not allow the verification of the message in case of a legitimate removal of the Observe option by an OSCORE-aware proxy.

**Comment by jimsch** [comment]
First, how is this different from the attacker just sending the messages to the client on its own w/o the server being involved?  Second, the client is going to discard the message received before doing any cryptographic processing because it will not be expecting to see a message with that message id.

I think you are trying to find a problem that does not really exist.  Christians problem is slightly more interesting in that the server will be forced to do work but I don't see a real way out of it as the attacker can do interesting things to keep the flow alive by doing it's own acks to the messages sent from the server.

**Comment by gselander** [comment]
One difference is the asymmetry of the work done by the attacker and those being attacked. Another is the distributed nature, where one client may get notifications sent from each server it sends a GET to. Whether this is a real problem depends on the application in question, but it should at least be a security consideration. But since it is possible to mitigate I would prefer if we also have some technical component, even if it is optional to implement.

**Comment by jimsch** [comment]
Yes you can talk about it as a security consideration, but there is nothing new that has been introduced as a new attack plane here.  The attack plane is probably not that large as the client will discard these messages as soon as they are received so only a small amount of work is done.  The problem is much more significant on the server side where cryptographic work would be done.  However, again there is nothing new.

In my implementation there would be a problem as I never send the duplicated options to the server/client.  Thus in my code what you are suggesting would not do any good.

**Comment by gselander** [comment]
OK. Let's just test an idea on how to address both the client and server issue discussed above: 

We allow Inner Observe for requests. Processing is identical to today except for the case when
 Inner is present AND Inner <> Outer. In that case OSCORE removes the Observe option, turning it to a non-Observe request.

Would that 
a) solve the issue?
b) be compliant with the relevant RFCs?
c) be a major change in the code?

(Alternatively, we could have that Inner always duplicates Outer for requests)

**Comment by chrysn** [comment]
On Tue, Apr 10, 2018 at 11:03:34PM -0700, Göran Selander wrote:
> We allow Inner Observe for requests. Processing is identical to today except for the case when
>  Inner is present AND Inner <> Outer. In that case OSCORE removes the Observe option, turning it to a non-Observe request.

How I read this is "We'd allow a client to send Observe:1 in the inner
message to explicitly mark this as a non-observation".

> Would that 
> a) solve the issue?

This would avoid the attack of an adversary upgrading a GET to a
GET+observe to make the server do needless work, but only if the client
spends 2 bytes on explicitly saying that a request is not an observation
on every single non-observation request.

> b) be compliant with the relevant RFCs?

It's a bit of a stretch, as it'd appear as a deregistration where there
was no previous registration. I think it's probably compliant, though in
twisted way.

> c) be a major change in the code?

Not for me.

> (Alternatively, we could have that Inner always duplicates Outer for requests)

I'd prefer that variant over the above. It would be an additional 1B for
every observe instead of 2B for every non-observe.

My answers then are a) yes for the same case, b) yes, and c) not-for-me.

**Comment by gselander** [comment]
What I was thinking was the following:

"We allow a client to send Observe:0 in the inner message to explicitly mark this is an registration, and we allow a client to send Observe:1 to explicitly mark this as a deregistration"

(Or in the alternative variant "We require a client to send Observe:0 in the inner message to explicitly mark this is an registration, and we require a client to send Observe:1 to explicitly mark this as a deregistration")

Does that change the conclusion or do you see advantages doing it in another way?

Edit: Francesca pointed out I missed to spell out that in either case it is assumed that the duplicate Outer Observe is always set.

**Comment by fpalombini** [comment]
Just to make sure we all understand each other.

The issue we are trying to solve is that of an attacker on path modifying the request/response to add/remove the observe. This may lead to: 

- on server's side, processing overload of the server if observe is added to request
- on client's side, the attacker might pick one specific notification and only fw that to the client (note: yes this is allowed by observe as of now. but we can mitigate that so why not)

To solve this, we can add the following modification to the doc:

1. sec considerations of the above
2. proposed solutions to solve the above (this is mandatory to implement):

    2.1. say that Observe is both Inner and Outer; if Observe is used, it MUST be sent outer, and it MAY be sent inner. If it is sent inner, the inner MUST have the same value as the outer.

    2.2. additions to processing: what to do when Observe is not the same Inner and Outer (including: Inner Observe is present but not Outer, Inner and Outer are present but with different values). We can discuss the details here, Göran was suggesting (for requests): discard Observe all the time, except if Inner is present, Outer is present, and Inner = Outer (no modifications to the processing for Observe responses).

Göran's second alternative was to change 2.1 so that "if Observe is used, it MUST be sent outer, and it MUST be sent inner."

Göran was asking if you think this would be Ok, and how much change in the code would that be.


@jimsch What do you mean when you say:

> In my implementation there would be a problem as I never send the duplicated options to the server/client. 

Do you mean you don't send duplicated options to the CoAP stack? I don't understand this sentence.

**Comment by ektrah** [comment]
Ignore outer Observe for a moment.

What would need to be done to make end-to-end Observe work on top of polling with GET requests?

**Comment by gselander** [comment]
Inner Observe works just fine with OSCORE standard processing of inner options. But it does of course not take into account proxy operations. Was this the question?

**Comment by ektrah** [comment]
Then inner and outer Observe are completely orthogonal, no? A client can end-to-end observe a resource at a server, but the last hop to the server can freely decide to use polling. A client can end-to-end poll a resource at a server, but the last hop to the server can freely decide to optimize this by observing the resource.

**Comment by gselander** [comment]
If a client makes an end-to-end observe using inner observe, without using outer observe, wouldn't the intermediary drop all notifications but the first? That is at least my understanding of why they are not orthogonal.

**Comment by jimsch** [comment]
Looking at chrysn's response:
a)  I agree
b)  I agree
c)  this would be a small change that would not be a problem.  Only one version of Observe is presented to the server application.  I have no ability to let a client or server know that there are two different versions of an option.  A coap message as presented to the application using the stack is - Here is the set of options.   This means, among other things, that I do not deal well with the issue of having two different values of the client saying send me blocks of size X (one inner and one outer).

Intermediaries are explicitly permitted to unregister an observation.  If a proxy is shutting down for some reason it would be reasonable for it to tell the server of that fact by removing all observations that it currently has open.  I would hope/expect that it would also relay this information down to any of its subscribers.  (Not sure what would happen for my code as observe processing is done after secure processing is done.) I do not believe that it is ever legal to fix the problem of a third party shutting off an observation relationship.

Something that I just thought of that does need to be put into the document is that a proxy CAN NOT turn an observation request into a polling request if OSCORE is present in a message.  The proxy sending the same message twice to the server (i.e. polling) would result in the message being ignored the second time that it is sent as it would be detected as a duplicate message in the OSCORE layer.

**Comment by gselander** [comment]
Thanks Jim. There are certainly limitations:

> Intermediaries are explicitly permitted to unregister an observation.

Yes, by RFC 7641, but note that since an intermediary does not have the security context, it is not able to originate a request which deregisters an observation that was originated with an OSCORE request copied hop by hop from client to the server. The only thing an intermediary can do to an OSCORE message which will be accepted by the endpoints (in the current specification) is to change the Observe option. The only thing, essentially, an intermediary can meaningfully do to an OSCORE message, besides copying the Observe option when present, is to remove Observe 0. The purpose of inner Observe would be to inform the server that an intermediary node has made some change to Observe, enabling the server to produce a response that is meaningful if it reaches the client. 

> a proxy CAN NOT turn an observation request into a polling request if OSCORE is present in a message.  

Right, if a proxy does not include Observe 0 in the next hop, it will turn into a single request and produce a single response.

**Comment by chrysn** [comment]
On Wed, Apr 11, 2018 at 10:53:07AM +0000, ektrah wrote:
> Then inner and outer Observe are completely orthogonal, no?

Good point, we did not consider that in detail before.

If the proxy decides to turn an observation into polling, it would be
put off by the Max-Age:0 sent with the response; it would need to keep
polling very frequently, and the first response would get back with an
error.

(Technically, the server *might* keep sending responses if it
the inner method is safe and it implements certain optimizations, but we
do not specify them because they're easy to get wrong -- so in practice,
the second response is always an error).

To the client, this will look a bit odd ("How can the server think I'm
doing a replay when I did not even send a second request?"), but
probably it'd treat it as an observation gone wrong.


The other direction (a non-observe being turned into observation by a
very motivated proxy) can not happen b/c those requests are POSTs. (And
that's good because no future request would ever match the cache key).


So in summary, they really are not.

**Comment by chrysn** [comment]
On Wed, Apr 11, 2018 at 10:52:35AM -0700, Jim Schaad wrote:
> Only one version of Observe is presented to the server application.

Same here. I pass a message into an unprotect() method and get a message
out; that message can just have a regular observe option.

 
> Intermediaries are explicitly permitted to unregister an observation.
> If a proxy is shutting down for some reason it would be reasonable for
> it to tell the server of that fact by removing all observations that
> it currently has open.

IMO it would send a final 5.03 Temporarily Unavailable, ideally with a
Max-Age indicating when the proxy expects to be back up.


What we can not do right now is have the origin server send a similar
5.03 as a *protected* message when it is shutting down -- if it wants to
send any protected data to its client (say, a diagnostic message), it'd
need to wrap that in a protected 5.03 which is a 2.05 (with still active
obs because that mustn't go away), and later send an unprotected 5.03
without the diagnostic message so that an intermediary also knows that
the observation is over.

On Wed, Apr 11, 2018 at 10:28:28PM -0700, Göran Selander wrote:
> Yes, by RFC 7641, but note that since an intermediary does not have
> the security context, it is not able to originate a request which
> deregisters an observation that was originated with an OSCORE request
> copied hop by hop from client to the server. The only thing an
> intermediary can do to an OSCORE message which will be accepted by the
> endpoints (in the current specification) is to change the Observe
> option. The only thing, essentially, an intermediary can meaningfully
> do to an OSCORE message, besides copying the Observe option when
> present, is to remove Observe 0. The purpose of inner Observe would be
> to inform the server that an intermediary node has made some change to
> Observe, enabling the server to produce a response that is meaningful
> if it reaches the client. 

The proxy that shuts down will set Observe:1. By the processing you
suggested, the server would ignore that and happily keep sending
messages on that token -- and the next notification will elict a RST
from the proxy, provided it is still there; might also be an ICMP error,
and what if it was on a TCP connection?

I think that this shows that we can use an inner observe to limit what
can be started, but we should not build applications that use Observe
options in non-transparent ways. Other protocol extensions like CoAP
over TCP rely on observations to work as expected.

(This is not saying that Observe can't be extended, but it needs to be
done carefully and in a compatible and transparent way).

**Comment by fpalombini** [comment]
So just to be clear, you are suggesting that only registrations (Requests with observe=0) are sent Inner by the client? This is still a problem. An "intermediary-initiated" deregistration will not contain an OSCORE option and will not be processed by an OSCORE server, creating the same issue you describe. Doesn't matter if we define (Observe=1) as only outer, the OSCORE server as of now does not process messages from anybody else than the OSCORE client.

And we do allow RST to be processed, although not protected by OSCORE... this means that the proxy can use that to deregister and solve the issue you describe... A consequence of this behaviour is that anybody can deregister an observation without the endpoint knowing... But maybe this is just equivalent to DoS, so acceptable? What do you think?

**Comment by chrysn** [comment]
Ad RST: We need to let the proxy deregister an observation; discarding the RST or an outer Observe:1 would just mean that we keep spamming the proxy with notifications it will not forward any more.

After having chatted with Göran before, I'd sketch the proposed mitigation for "proxy initiates observation w/o client having authorized it" as follows:
* Whenever a client starts or updates an observation, it sets inner Observe:0
* Servers respect the outer observe option (whether it's register or deregister), but will only accept an observation if there is an inner Observe:0 too.
(There is no "authenticated deregistration", because we need to allow unauthenticated deregistration anyway. The only thing the inner Observe:0 is saying is "Trust the outer observe, I did intend to set one up".)

So no, it's non only registrations that are sent with inner Obs:0 by the client, but registrations, reregistrations and deregistrations (the latter could leave it out just as well, though).

**Comment by fpalombini** [comment]
> Ad RST: We need to let the proxy deregister an observation; discarding the RST or an outer Observe:1 would just mean that we keep spamming the proxy with notifications it will not forward any more.

What I was saying is that we already allow RST in the document as of now. This does not require a change in the doc, it is already the case, RST are not discarded, a proxy can use that to de-register.

> Servers respect the outer observe option (whether it's register or deregister), but will only accept an observation if there is an inner Observe:0 too.
(There is no "authenticated deregistration", because we need to allow unauthenticated deregistration anyway. The only thing the inner Observe:0 is saying is "Trust the outer observe, I did intend to set one up".)

I have a problem with this. (Assuming by "respect the outer observe option" you mean process it, and by "accept an observation" you mean process a registration or reregistration). I still don't see how an intermediary can deregister with your proposal. First, the proxy does not even know what resource to deregister (it's encrypted) so it would just deregister /? Second, the proxy is not going to include the OSCORE option. The proxy is not "copying" a previous client's request, but it is initiating its own (acting as a client), but it does not have a security association with the server, so its request will be rejected by the server. It will not get to "accepting the outer observe", it will fail at "expected OSCORE Option". 

Am I missing anything?

**Comment by fpalombini** [comment]
What I am considering an acceptable solution, following the thread here and the discussion above is:
- Whenever a client starts or updates an observation, it sets inner Observe:0 and outer Observe:0
- Whenever a client wants to stop an observation, it sets inner Observe:1 and outer Observe:1
- when the server receives an Observe, checks that inner == outer; if so, it process accordingly. if not, it only replies with one single response (to avoid overload);
    * if inner = 0 and outer = 1, the proxy is deregistering and will not accept more notifications, so it is useless to send several responses
    * if inner = 1 and outer = 0, the client is deregistering, so no need to send several responses, they won't reach it (no request will hit the cache key)
    * if inner is present and outer isn't, if inner is 0 the proxy is going to drop the notifications anyway. if inner is 1, the client meant to deregister anyway.
    * if outer is present and inner isn't, if outer is 1, the proxy is only going to accept one response anyway. if outer is 0, we don't allow it since no request will hit the cache key anyway.

Observe is outer in responses.
Proxies cannot deregister with outer observe if the client does not initiate it, but they can with RST.

Note that if, in the several hops, there is one intermediary that does not do observe but simple polling, the Server will not detect that, and will reply with several notifications, which will be lost at the hop that does polling
```
C         P         P         P        S
|  obs    |   get   |   obs   |   obs   |
|-------->|-------->|-------->|-------->|
|<--res---|<--res---|<--not---|<--not---|
|         |         |<--not---|<--not---|
|         |         |<--not---|<--not---|
```

What do you think about this?

**Comment by fpalombini** [comment]
The final text we included is:
- observe is inner (end-to-end) and it might be added outer for proxy processing (forwarding of notif), but the outer value is ignored by the endpoints
- we added considerations about intermediaries cannot explicitly cancel observations, unless applications define otherwise, but they can still cancel via other methods (RST)

See [version 13](https://tools.ietf.org/html/draft-ietf-core-object-security-13#section-4.1.3.5) for details.
