### ISSUE TITLE
Remove Master Salt default value

### ISSUE THREAD

**Issue by fpalombini** [core-wg/oscoap#229]
In order to avoid misunderstandings of the spec that are likely to lead to incompatibilities between implementations, we propose to remove the default value "empty string" for Master Salt in context derivation. Instead, our proposal is: The Master Salt is an optional parameter in the security context; note that if it is not set, the HKDF spec defines that a string of 0 is to be used instead.

Any comments? Thoughts?

**Comment by jimsch** [comment]
A default is a default.  It does not matter if it is a string of 0 or an empty string (which vague memory says converts to all zeros).

**Comment by gselander** [comment]
What Francesca is referring to is that since there is already a default value for the salt defined in HKDF  (if the salt is not provided it is set to a byte string of 0) then better not have a different default value for the Master Salt defined in OSCORE (the empty string). That may give the impression that the empty string and the byte string of 0 are different values of the Master Salt, which may lead to non-uniqueness of parameters.

**Comment by jimsch** [comment]
Excerpt from RFC 5869

Inputs:
      salt     optional salt value (a non-secret random value);
               if not provided, it is set to a string of HashLen zeros.

There is no difference and providing a default means that you do not need to change the salt value to something else if a different hash algorithm is used.

**Comment by fpalombini** [comment]
Our confusion came from the term "not provided" in RFC 5869: it wasn't clear to us (from the paragraph you quote) that "salt = empty byte string" and  "salt not provided" is equivalent. So we'll go back to a default but we'll note that, for implementations of HKDF, we assume empty byte string converts to a string of zeroes.

**Comment by fpalombini** [comment]
Done now in 6134d854
