### ISSUE TITLE
Notes on test vectors

### ISSUE THREAD

**Issue by chrysn** [core-wg/oscoap#241]
I'm just adding tests to aiocoap based on the test vectors, and the KDF stuff was uneventful.

For vector 4, I had to come up with some assumptions you made which are not explicit:
* The token and message ID for the should be taken from the unprotected message. I'm not sure whether the spec actually says that protecting a request keeps the token and MID intact (IMO it makes little sense, as typically one side of the conversion has no concept of them), but it might be a good point here to point it out. (eg. "For this test vector, the protected message has the same MID and token as the unprotected message.")
* The value of TBD1 is 9. Other implementors might benefit from a note a la "[ These tests assume that the value assigned by IANA to TBD1 is 9. If that differs, the RFC editor is asked to update the test vectors with data provided by the authors. Please remove this line before publication. ]"
* C.7 and following: The sender sequence number is immaterial, but to arrive at the protected response, we'd need to know the partial IV of the sent message (The assumption that it was sent with seqno=20 as in C.4 worked but was a validated guess).
* The tokens bear a striking familiarity to the odd ones I produced earlier in aiocoap (4 bytes length, 2 bytes counter, leading zeroes), which are (contrary to best practice) not very compact. I briefly thought about suggesting shorter ones, but then again, if the (permissible) leading zeros tip over an implementation in the test vectors before it gets tipped over by a communication peer, all the better.

(I have skipped the server parts of C.2.2 and C.2.3 and the later C.8 and C.9 for being just orthogonal completion of stuff tested earlier, and don't pass C.6 yet because KID context encoding is missing -- but for the rest, your values match what my implementation produced after following the document's changes on first attempt, so there should be only little danger of error by copying someone else's mistakes. Right now, the greatest danger-to-interoperability-even-after-plugtests I see is that all our collective mental models did not follow a change that was made lately in the text, but where would we get someone to implement things from -14 without having read any earlier version?)

**Comment by chrysn** [comment]
Apologies about the point on C.7: It does say it is a response to the request from C.4, so please scratch that paragraph.

Adding C.6 to my code, two more things came up:
* The (odd) protected CoAP request in C.6 does not include the (correct) ciphertext two lines above it, I suppose that got looked over during updates.
* It is not fully clear to me from the specification under which conditions a KID Context should be encoded in the "kid context" unprotected field (and therefore in the "h" flag). My understanding is that it's application dependent whether it's set. In that case, the case description for C.6 should include a line that "The application decides to encode the KID context in the request." (It could also choose not to; wouldn't change the ciphertext but would make the OSCORE option 8 bytes shorter). May a KID Context be present in a response? (I would, from the progression of the earlier test vectors, have expected a response to the C.6 request as a C.9).

**Comment by fpalombini** [comment]
Hi @chrysn! sorry for the delay, I was on vacation, but I am back now :)

> The token and message ID for the should be taken from the unprotected message. I'm not sure whether the spec actually says that protecting a request keeps the token and MID intact (IMO it makes little sense, as typically one side of the conversion has no concept of them), but it might be a good point here to point it out. (eg. "For this test vector, the protected message has the same MID and token as the unprotected message.")

Yes I agree, that is completely implementation specific. To be even more precise, it is not sure that the unprotected message would even be created at all by the implementation, before creating the protected message, on the contrary. I did choose to have the same values for both protected and unprotected messages, as I think that should help readers to see which parts of the message would change, when OSCORE is added. I will add a sentence to point out that they are the same, as you suggest. 


> The value of TBD1 is 9. Other implementors might benefit from a note a la "[ These tests assume that the value assigned by IANA to TBD1 is 9. If that differs, the RFC editor is asked to update the test vectors with data provided by the authors. Please remove this line before publication. ]"

Yes, there is some hidden comment text in the .md document about this, for us author not to forget. Also, there was a talk of early registration for OSCORE as a CoAP option, also related to this. I will add some (explicit) text as you suggest, with request to remove before publication, that's a good idea.

> The tokens bear a striking familiarity to the odd ones I produced earlier in aiocoap (4 bytes length, 2 bytes counter, leading zeroes), which are (contrary to best practice) not very compact. I briefly thought about suggesting shorter ones, but then again, if the (permissible) leading zeros tip over an implementation in the test vectors before it gets tipped over by a communication peer, all the better.

That's probably because I started from your implementation (some time ago, after it was interop tested), updated it to the latest version, to produce the test vectors :D Thanks for that involuntary help! But yes I agree, I don't think it matters that much, if they are long or short, and if a different bug is found because of that, all the better.

> (I have skipped the server parts of C.2.2 and C.2.3 and the later C.8 and C.9 for being just orthogonal completion of stuff tested earlier, and don't pass C.6 yet because KID context encoding is missing -- but for the rest, your values match what my implementation produced after following the document's changes on first attempt, so there should be only little danger of error by copying someone else's mistakes.

Good to see that my update and your update work :) (even though the base was the same, but we interop after that, so all should be fine...)

> Right now, the greatest danger-to-interoperability-even-after-plugtests I see is that all our collective mental models did not follow a change that was made lately in the text, but where would we get someone to implement things from -14 without having read any earlier version?)

Agreed... but I think it is already a good success with the result of the progressive interops! (for anybody else reading: reports [here](https://ericssonresearch.github.io/OSCOAP/) )

> The (odd) protected CoAP request in C.6 does not include the (correct) ciphertext two lines above it, I suppose that got looked over during updates.

Good catch, thanks! Will fix.

> It is not fully clear to me from the specification under which conditions a KID Context should be encoded in the "kid context" unprotected field (and therefore in the "h" flag). My understanding is that it's application dependent whether it's set. In that case, the case description for C.6 should include a line that "The application decides to encode the KID context in the request." (It could also choose not to; wouldn't change the ciphertext but would make the OSCORE option 8 bytes shorter). May a KID Context be present in a response? (I would, from the progression of the earlier test vectors, have expected a response to the C.6 request as a C.9).

That's right, this is application dependent, whether this value needs to be sent. I will try to explicitly say what you suggest, although that was my intent with the sentence "for an OSCORE protected CoAP GET request carrying the ID Context in the message" (it can't hurt to repeat that that is application specific...)

Again, for kid context in responses, that is also application specific. We leave open the possibility of sending it in responses. Do you think having a C.9 with an example for when the kid is carried in responses would be useful? I didn't think that would add much, but I could add it if you think so.

**Comment by chrysn** [comment]
> Do you think having a C.9 with an example for when the kid is carried in responses would be useful? I didn't think that would add much, but I could add it if you think so.

I don't thin it'd add value to the test vectors if one is present, especially given that it has no impact on the ciphertext. (I doubt it'd be valid to have a different context ID than the one of the request).

**Comment by fpalombini** [comment]
The ciphertext would only be different (from the one without Context ID) because the keys and nonces would be different because the whole context derivation is different... 

And that's right, it must be the same on both endpoints.
