### ISSUE TITLE
Security context not found

### ISSUE THREAD

**Issue by Niarazan** [core-wg/oscoap#242]
Hi,
I am trying to implement oscore with linux and i am having trouble at the server side.
I have implemented the client and server on the same local machine.
Client sends the get request with oscore protected to the server, server receives the message and while trying to decode the packet from "oscore_decode_message" function, i get an error message saying "security context not found". While debugging i found out that
The length of the object-security is 1. Also the first index of the object_security (option_value[0]) is 0.
Are these the right value to for the object-security_length and object_security (option_value[0]) ? 
And "oscore_decode_option_value" function cannot set the partial_iv, kid_context and key_id to the cose object so while trying to get the context from "oscore_find_ctx_by_rid" function, the ctx variable is null..

So can you please provide any suggestions regarding the issue? Would be really really grateful to you..
Waiting for your response...Thanks in advance

Best Regards,
Nirajan Shrestha

**Comment by gselander** [comment]
Hi Nirajan,

Sorry for delayed response, you managed to pick the time when everyone was on vacation.

Which version of the draft are you implementing? The current version is -14.

I'm reading your questions and and they seem to partly assume familiarity with the code. Have you compared your values with the test vectors (Appendix C)? From the test vectors you can e.g. see what length and value of the OSCORE option you should get for a given input. 

Would it be possible to rephrase your questions in terms of the specification? Either if you have specific questions on some section in the draft, or if your implementation does not give the same values as the test vectors, e.g.: "With the input in test vector 4 (Appendix C.4) I get a different OSCORE option value: . . . ". That could be a starting point for identifying if the error is on the client or server side.

Hope that helps.

Best regards,
Göran Selander

**Comment by fpalombini** [comment]
Hi @Niarazan ,

It sounds as your issue is more about using an existing implementation than with the specification itself.
From the names of the functions, it sounds like you might be using [this code](https://github.com/Gunzter/contiki-ng/tree/oscore_12), is that correct?

From the error you get, it sounds like the recipient_id on the server side doesn't match the sender_id the client sends in the message, so the server is not able to find it when it receives the message. Can you please check:

-  you are setting the context parameters on the server, as it is done in [this example](https://github.com/Gunzter/contiki-ng/blob/oscore_12/examples/oscore/oscore-example-server.c) (lines 69 to 72), 
- you are setting the context parameters on the client, as it is done in [this example](https://github.com/Gunzter/contiki-ng/blob/oscore_12/examples/oscore/oscore-example-client.c) (lines 51 to 54), 
- that your receiver_id parameter matches the sender_is parameter in the client,
- that you derive the context (using oscore_derive_ctx function) and associate it with the server as it is done in the examples

From the values you are sending in your OSCORE option, it seems like the option is set uncorrectly, with no sender id, and that you are not doing the steps above.

Let me know if that helps!

**Comment by Niarazan** [comment]
Hi  Göran,

Thank you very much for your reply..

Yes you are right that i am using an existing implementation as you have
mentioned. I am using the same OSCORE implementation for contiki.
I have checked the context parameters as you have said and the sender_id in
client matches with the receiver_id in the server.
I am not getting the previous error now as i figured out that i mistakenly
changed a return value to 1 in one of the functions in the implementation.

Now the problem is my program does not get inside the "
*oscore_decode_message()*" function defined in "*oscore.c*" file *code
line: 177* after parsing the message in the server side through "
coap_parse_message" function in  "*coap.c*" file *code line 445* . The
server detects the * "COAP_OPTION_OSCORE"*  set in the message and
successfully matches the switch case statement in "*coap.c*" file *code
line 667.
Link:"https://github.com/Gunzter/contiki-ng/blob/oscore_12/os/net/app-layer/oscore/coap.c
<https://github.com/Gunzter/contiki-ng/blob/oscore_12/os/net/app-layer/oscore/coap.c>".*

But the "*object_security"* value is not null and the "
*object_security_length*" is 0 so the if statement result is false which is
implemented before invoking "*oscore_decode_message()*" function in "
*coap.c*" file *code line 730.*

Also i checked the "*object_security_length*" value in the client side in
the "*oscore.c*" file *code line 325*;
 *link*: *https://github.com/Gunzter/contiki-ng/blob/oscore_12/os/net/app-layer/oscore/oscore-support/oscore.c
<https://github.com/Gunzter/contiki-ng/blob/oscore_12/os/net/app-layer/oscore/oscore-support/oscore.c>.*

The returned value is 0. And mistakenly, i set this returned value to 1 and
that was the reason the program could run the "*oscore_decode_message()*"
function.

I am sending a GET request from the client and in the "
*oscore_prepare_message*" function, the payload is being set in the request
message in the client side using "coap_set_payload()" function *code line
326. *I think the get request should not contain payload right? Please
correct me if i understood wrong..

 Now i get "server not responding" response from the server and i cannot
figure out what has gone wrong. I can provide further details to you if you
require..
I really appreciate your help Göran. Hope to hear from you again..

Best Regards,
Nirajan

**Comment by fpalombini** [comment]
Hi Nirajan,

I don't know how you can have 0-length OSCORE (Object-Security in the code) option, if you set everything correctly in the client. 

> The returned value is 0. And mistakenly, i set this returned value to 1 and
that was the reason the program could run the "*oscore_decode_message()*"
function.

To run OSCORE with this implementation, you shouldn't be changing values in coap.c or oscore.c, but only in the examples (such as oscore-example-client.c )

> I am sending a GET request from the client and in the "
> *oscore_prepare_message*" function, the payload is being set in the request
> message in the client side using "coap_set_payload()" function *code line
> 326. *I think the get request should not contain payload right? Please
> correct me if i understood wrong..

No that's right, but OSCORE actually "hides" a GET req into a PUT (for privacy) and uses that payload to carry encrypted options, so that's not a problem. That is decoded correctly on the other endpoint.

I think you get "server not responding" because the parsing of the OSCORE option does not go through.

I would need to see your client and server code, to be able to help you more. You can send them here: francesca.palombini at ericsson.com.

I will close this issue now, since it is unrelated to the spec.

Francesca
