### ISSUE TITLE
In section 4.1.3.3. Uri-Port dissapears from the example

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#260]
In the example in section 4.1.3.3. there is an Uri-Port given in the Proxi-Uri decomposition. This disappears in the resulting OSCORE Uri-* and Proxy-Uri options.
Although this is the default CoAP portnumber, it is a bit confusing for the reader, perhaps we should add some explanatory sentence?

**Comment by fpalombini** [comment]
It does not really disappears, as the original Proxy-Uri did not contained it either: 

> Assume that the original CoAP message contains:
> 
> Proxy-Uri = “coap://example.com/resource?q=1”

So it really just first appear then disappear, as its value is the default in both the initial and the final Proxy-Uri.
But I agree that we could clarify that it is the default value, what about:

OLD:
Uri-Port = “5683”
NEW:
Uri-Port = “5683” (default)

Or,

add at the end of the section:
"Note that the Uri-Port is not part of the original or final Proxy-Uri since the default value is used."  (there is a reference to more details just after)

**Comment by gselander** [comment]
The first proposal is good.
