### ISSUE TITLE
Don't put things in the Security Context that are not needed

### ISSUE THREAD

**Issue by jimsch** [core-wg/oscoap#4]
Section 3.1 - If Base Key and the IDs are not needed once the security context has been setup, remove them from the definition of the context and just make them prerequisites for the context algorithm creation you are defining.

**Comment by fpalombini** [comment]
following mail discussion: [see archive](https://mailarchive.ietf.org/arch/msg/core/-Z57TmweeZxx9T0oNidZbhiPsTI)

For now, we are keeping both Base Key and ID in the context, to consider for a future update.
On the other hand, we'll consider the usefulness of Sender ID in external AAD and in case remove it from v-01.

**Comment by gselander** [comment]
While the Sender ID is not strictly needed in the external_aad_resp in the unicast setting, I would like to keep it like this in this draft pending a decision on what happens to the multicast security draft, instead of moving it to that draft and potentially moving it back later. In the end we should have exactly the right content it the respective draft, for now I'd just like to make sure that the protocol is well defined and contains the necessary information fields and not optimize which fields are defined in what draft.

**Comment by fpalombini** [comment]
This issue is obsolete now. I'll close it unless objections.
