### ISSUE TITLE
Clarify the handling of the differents parts of the OSCOAP context

### ISSUE THREAD

**Issue by LudwigSeitz** [core-wg/oscoap#43]
As per Christian Amsüss' message from 2017-01-04 we should clarify how the different parts of the OSCOAP context are used. I think an example would go a long way to make this more clear.

**Comment by chrysn** [comment]
Maybe wording it like "to send using *its* Sender Context and verify messages received using *its* Recipient Context" (instead of "the") when referring to an endpoint's context could enhance readability here.

**Comment by LudwigSeitz** [comment]
Good point! I've made a few changes, I might need to go over the text once more to catch more of these.

**Comment by fpalombini** [comment]
Hello, sorry to be late, slowly catching up.

@chrysn Thanks for your comment from [1], and good point about using _its_ instead of _the_ in the sentence above, we will include that very soon. I'd like to quickly re-quote the point where we currently define the security context:

> The security context is the set of information elements necessary to carry out the cryptographic operations in OSCOAP. [... ] For each endpoint, the security context is composed by a "Common Context", a "Sender Context" and a "Recipient Context". The endpoints protect messages to send using the Sender Context and verify messages received using the Recipient Context, both contexts being derived from the Common Context and other data

I think the part you may have misunderstood/overlooked in the text is the following:

>  For each endpoint, the security context is composed by a "Common Context", a "Sender Context" and a "Recipient Context".

Do you have any other comment that may help clarifying the misunderstanding? (The point is I don't really see how to modify this to make it more understandable)

@jimsch Thank you for input as well :) Trying to improve here, in your mail [2] you said: "Part of the confusion that you might be having at this point is the fact that there is another draft running around draft-tiloca-core-multicast-oscoap where you end up with a single sender context, but potentially one recipient context for each of the multicast receivers which can reply.  Since they did not want to make a clean separation between these documents about how the context structures are setup, I find that the section is a bit sloppy." I'm interested in understanding better what do you mean: 
- how would you separate in a cleaner way? Currently, OSCOAP is the standalone document, while multicast OSCOAP is of course dependent on OSCOAP. I'm all for cleaner and more readable, if you have a good suggestion.
- what do you think is sloppy? What can we improve? More feedback would be greatly appreciated :)

[1] https://mailarchive.ietf.org/arch/msg/core/328ja7ggGRLuvfpb2XIO_iMhNjg (second point)
[2] https://mailarchive.ietf.org/arch/msg/core/zbaJQDR0KMTw1tHyebBzzc-7CZI
