### ISSUE TITLE
Clarify that tag is algorithm dependent.

### ISSUE THREAD

**Issue by gselander** [core-wg/oscoap#49]
Last comment of https://mailarchive.ietf.org/arch/msg/core/t7dTEVvBuzp_a0ppCKlz3AYQRzg

**Comment by fpalombini** [comment]
We are planning on removing the use of the tag and use the whole ciphertext instead in the Blockwise option (section 4.3.1.3.), since the tag is algorithm dependent and may be difficult to extract. What do you think, @jimsch and @chrysn?

**Comment by chrysn** [comment]
On Mon, Jan 16, 2017 at 05:35:41AM -0800, fpalombini wrote:
> We are planning on removing the use of the tag and use the whole
> ciphertext instead in the Blockwise option (section 4.3.1.3.), since
> the tag is algorithm dependent and may be difficult to extract. What
> do you think, @jimsch and @chrysn?

disclaimer: i haven't implemented that part yet (only outside
blockwise), and just read through the relevant parts again.

right on the cause: keeping the whole ciphertext around would be 1k of
RAM data that would need to be kept around for every ongoing blockwise
transfer. wouldn't the partial iv of the last block be sufficient? after
all, if the last block was received valid, the seqno was unique. this
would preclude blockwise transfers spanning contexts, but i'd be careful
with such transfers even if they were allowed.

maybe slightly off topic: how much consideration and discussion has that
block mechanism received before? it introduces keeping state where as an
implementor i'd try to avoid that, and there might be other easier
options that would work statelessly, that is

* mandating ETags for block2 responses (already recommended for
  blockwise anyway; "An advisory would be welcome to inject an old
  packet that's block 2/1/1k of the ETag 012345 response to a given URI,
  because the server already confirmed that the ETag is valid in
  whichever response we consider fresh, and the rest could have been
  cached just as well"), and

* possibly a "client ETag" option that could group together block1
  messages (might be useful in other situations too, eg. when changing
  protocols or addresses)?

**Comment by jimsch** [comment]
Extracting the tag can be hard, however I don't know that keeping the entire ciphertext is going to be much better given that you might need to keep several of these around for an amount of time to deal with doing an Observe on a large data time - need to keep this value for every different Observe that is currently doing the block transfer -- which is all of them.

@chrysn - the reason for using the crypto tag is to have the ability to establish that the entire message has been integrity protected rather than just the independent pieces.  Any value which is not representative of the entire message such as an ETag would no fulfill this requirement.

**Comment by jimsch** [comment]
While I made the statement that the tag can be in different places, I would not worry about this as being a reason for moving from the tag to the cipher text.  With all of the algorithms we are currently likely to use, it will always be appended to the end of the cipher text.

**Comment by chrysn** [comment]
The topic of whether ETag-like message protection is (or can be made) sufficient seems unsuitable for continuation here; I've taken it [to the CoRE mailing list](https://mailarchive.ietf.org/arch/msg/core/oQmnpdA8JbNyCBx-9HCy-ddtE8I).

**Comment by emanjon** [comment]
Will add text explaining the key, IV, etc are algorthm dependand. All mensioning of AEAD "tag" will be removed.
